//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IslandsApp1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IslandsApp1.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buildings {
            get {
                object obj = ResourceManager.GetObject("buildings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap explosions {
            get {
                object obj = ResourceManager.GetObject("explosions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flames {
            get {
                object obj = ResourceManager.GetObject("flames", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] island1 {
            get {
                object obj = ResourceManager.GetObject("island1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 168
        ///60
        ///96
        ///96
        ///72
        ///108
        ///192
        ///72
        ///168
        ///84
        ///144
        ///96
        ///120
        ///108
        ///96
        ///120
        ///288
        ///48
        ///264
        ///60
        ///240
        ///72
        ///216
        ///84
        ///192
        ///96
        ///168
        ///108
        ///144
        ///120
        ///120
        ///132
        ///96
        ///144
        ///336
        ///48
        ///312
        ///60
        ///288
        ///72
        ///264
        ///84
        ///240
        ///96
        ///216
        ///108
        ///192
        ///120
        ///168
        ///132
        ///144
        ///144
        ///120
        ///156
        ///96
        ///168
        ///360
        ///60
        ///336
        ///72
        ///312
        ///84
        ///288
        ///96
        ///264
        ///108
        ///240
        ///120
        ///216
        ///132
        ///192
        ///144
        ///168
        ///156
        ///144
        ///168
        ///120
        ///180
        ///96
        ///192
        ///384
        ///72
        ///360
        ///84
        ///336
        ///96
        ///312
        ///108
        ///288
        ///120
        ///264
        ///132
        ///240
        ///144
        ///216
        ///156
        ///192
        ///168
        ///168
        ///180
        ///144
        ///192
        ///120
        ///204
        ///96
        ///216
        ///408
        ///84
        ///38 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string island1d {
            get {
                return ResourceManager.GetString("island1d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] island2 {
            get {
                object obj = ResourceManager.GetObject("island2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24
        ///60
        ///120
        ///36
        ///144
        ///48
        ///120
        ///60
        ///96
        ///72
        ///72
        ///84
        ///48
        ///96
        ///48
        ///72
        ///48
        ///120
        ///72
        ///108
        ///96
        ///96
        ///120
        ///84
        ///144
        ///72
        ///144
        ///96
        ///96
        ///120
        ///192
        ///48
        ///240
        ///48
        ///240
        ///72
        ///264
        ///60
        ///288
        ///48
        ///336
        ///48
        ///312
        ///60
        ///288
        ///72
        ///264
        ///84
        ///264
        ///108
        ///384
        ///48
        ///408
        ///60
        ///432
        ///72
        ///384
        ///72
        ///384
        ///96
        ///288
        ///144
        ///264
        ///156
        ///240
        ///168
        ///240
        ///144
        ///264
        ///132
        ///216
        ///204
        ///240
        ///192
        ///264
        ///180
        ///288
        ///168
        ///336
        ///168
        ///312
        ///180
        ///288
        ///192
        ///264
        ///204
        ///240
        ///216
        ///336
        ///192
        ///312
        ///204
        ///288
        ///216
        ///264
        ///228
        ///240
        ///240
        ///264
        ///252
        ///336
        ///216
        ///432
        ///192
        ///48
        ///216
        ///96
        ///216
        ///72
        ///228
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string island2d {
            get {
                return ResourceManager.GetString("island2d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] island3 {
            get {
                object obj = ResourceManager.GetObject("island3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48
        ///96
        ///144
        ///72
        ///144
        ///96
        ///96
        ///120
        ///72
        ///132
        ///96
        ///144
        ///120
        ///132
        ///144
        ///120
        ///168
        ///108
        ///192
        ///96
        ///192
        ///120
        ///168
        ///132
        ///144
        ///144
        ///120
        ///156
        ///48
        ///216
        ///120
        ///180
        ///144
        ///168
        ///168
        ///156
        ///192
        ///144
        ///216
        ///156
        ///192
        ///168
        ///168
        ///180
        ///144
        ///192
        ///120
        ///204
        ///96
        ///216
        ///72
        ///228
        ///96
        ///240
        ///120
        ///228
        ///144
        ///216
        ///192
        ///192
        ///216
        ///180
        ///240
        ///168
        ///288
        ///168
        ///264
        ///180
        ///240
        ///192
        ///312
        ///180
        ///288
        ///192
        ///264
        ///204
        ///240
        ///216
        ///264
        ///228
        ///288
        ///216
        ///312
        ///204
        ///336
        ///192
        ///336
        ///216
        ///288
        ///240
        ///264
        ///252
        ///240
        ///264
        ///288
        ///264
        ///264
        ///276
        ///240
        ///288
        ///216
        ///300
        ///192
        ///312
        ///168        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string island3d {
            get {
                return ResourceManager.GetString("island3d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] island4 {
            get {
                object obj = ResourceManager.GetObject("island4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48
        ///72
        ///96
        ///72
        ///72
        ///84
        ///48
        ///96
        ///72
        ///108
        ///96
        ///96
        ///120
        ///84
        ///144
        ///72
        ///168
        ///60
        ///168
        ///84
        ///144
        ///96
        ///120
        ///108
        ///96
        ///120
        ///72
        ///132
        ///72
        ///156
        ///96
        ///144
        ///120
        ///132
        ///144
        ///120
        ///168
        ///108
        ///192
        ///96
        ///192
        ///120
        ///120
        ///156
        ///96
        ///168
        ///72
        ///180
        ///120
        ///180
        ///96
        ///192
        ///72
        ///204
        ///72
        ///228
        ///96
        ///216
        ///120
        ///204
        ///120
        ///228
        ///96
        ///240
        ///72
        ///252
        ///48
        ///264
        ///96
        ///264
        ///120
        ///252
        ///144
        ///240
        ///144
        ///264
        ///120
        ///276
        ///96
        ///288
        ///192
        ///264
        ///168
        ///276
        ///144
        ///288
        ///120
        ///300
        ///96
        ///312
        ///96
        ///336
        ///120
        ///324
        ///144
        ///312
        ///168
        ///300
        ///192
        ///288
        ///216
        ///276
        ///240
        ///264
        ///120
        ///348
        ///144
        ///336
        ///168
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string island4d {
            get {
                return ResourceManager.GetString("island4d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menu {
            get {
                object obj = ResourceManager.GetObject("menu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menuback {
            get {
                object obj = ResourceManager.GetObject("menuback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rectangles {
            get {
                object obj = ResourceManager.GetObject("rectangles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tiles1 {
            get {
                object obj = ResourceManager.GetObject("tiles1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tiles2 {
            get {
                object obj = ResourceManager.GetObject("tiles2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tiles3 {
            get {
                object obj = ResourceManager.GetObject("tiles3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
